//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archivo()
        {
            this.PrimerasEvaluaciones = new HashSet<PrimerasEvaluacione>();
            this.SegundasEvaluaciones = new HashSet<SegundasEvaluacione>();
            this.TercerasEvaluaciones = new HashSet<TercerasEvaluacione>();
        }
    
        public int id { get; set; }
        public string nombre_archivo { get; set; }
        public string mime { get; set; }
        public string path { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual Adjunto Adjunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimerasEvaluacione> PrimerasEvaluaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegundasEvaluacione> SegundasEvaluaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TercerasEvaluacione> TercerasEvaluaciones { get; set; }
    }
}
