//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColegioAsignado
    {
        public int id { get; set; }
        public string colegio_id { get; set; }
        public string jefe_departamento { get; set; }
        public string cargo { get; set; }
        public string antecedente { get; set; }
        public string periodo { get; set; }
        public string destinatario { get; set; }
        public string puesto { get; set; }
        public string universidad { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
