//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColegioAsignado
    {
        public int id { get; set; }
        public string colegio_id { get; set; }
        public string jefe_departamento { get; set; }
        public string cargo { get; set; }
        public string antecedente { get; set; }
        public string periodo { get; set; }
        public string destinatario { get; set; }
        public string puesto { get; set; }
        public string universidad { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
