//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public string usuario_id { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string genero { get; set; }
        public string nacionalidad { get; set; }
        public string curp { get; set; }
        public string domicilio { get; set; }
        public string colonia { get; set; }
        public string estado { get; set; }
        public string delegacion { get; set; }
        public string localidad { get; set; }
        public string codigo_postal { get; set; }
        public string telefono { get; set; }
        public string telefono_movil { get; set; }
        public string medio { get; set; }
    
        public virtual AspNetUsers Solicitante { get; set; }
    }
}
