//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvDisponible
    {
        public int id { get; set; }
        public string evaluador_id { get; set; }
        public int perfil_id { get; set; }
    
        public virtual Evaluador Evaluador { get; set; }
        public virtual Perfil Perfile { get; set; }
    }
}
