//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requerimiento()
        {
            this.Adjuntos = new HashSet<Adjunto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int perfil_id { get; set; }
        public string tipo_requerimiento { get; set; }
        public Nullable<System.DateTime> creacion { get; set; }
        public Nullable<System.DateTime> modificacion { get; set; }
    
        public virtual Perfil Perfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjunto> Adjuntos { get; set; }
    }
}
