//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_SAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SACEntities : DbContext
    {
        public SACEntities()
            : base("name=SACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nivel> Niveles { get; set; }
        public virtual DbSet<Perfil> Perfiles { get; set; }
        public virtual DbSet<Procedimiento> Procedimientos { get; set; }
        public virtual DbSet<Requerimiento> Requerimientos { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Solicitud> Solicitudes { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<Adjunto> Adjuntos { get; set; }
        public virtual DbSet<Archivo> Archivos { get; set; }
        public virtual DbSet<PrimerasEvaluacione> PrimerasEvaluaciones { get; set; }
        public virtual DbSet<SegundasEvaluacione> SegundasEvaluaciones { get; set; }
        public virtual DbSet<TercerasEvaluacione> TercerasEvaluaciones { get; set; }
        public virtual DbSet<Evaluador> Evaluadores { get; set; }
        public virtual DbSet<SolicitudDeshechada> SolicitudesDeshechadas { get; set; }
        public virtual DbSet<Colegio> Colegios { get; set; }
        public virtual DbSet<ColegioAsignado> ColegiosAsignados { get; set; }
    }
}
